const Partner = require("../models/Partner");
const ResellerBillingConfig = require("../models/ResellerBillingConfig");
const ResellerInvoice = require("../models/ResellerInvoice");
const ScreenLicensePurchaseOrder = require("../models/ScreenLicensePurchaseOrder");
const { RESELLER_LICENSE_TERM_MONTHS } = require("../config/constant");
const logActivity = require("../utils/logActivity");
const notifyPartner = require("../utils/notifyPartner");

/* ============================================================
   RESELLER BILLING

   EVERY LICENCE PURCHASE IS ITS OWN BILL, with its own billing
   cycle that starts on the day the licences were bought.

   Example: a reseller buys 200 licences at Rs. 300 per screen per
   month on 6 Oct 2026, on a quarterly billing cycle.
     per month            200 x 300        =   60,000
     12-month term        60,000 x 12      = 7,20,000 (+ GST)
     each quarterly bill  60,000 x 3       = 1,80,000 (+ GST)
   The first bill is raised on 6 Oct 2026 — the day of purchase —
   and the next ones on 6 Jan, 6 Apr and 6 Jul 2027: four bills
   that together make up the 12-month total.

   If the reseller buys more licences later, that purchase is a
   NEW bill: its own price (whatever the plan was that day), its
   own cycle starting from its own purchase date. Purchases are
   never merged into one another's bills.

   A bill is charged in advance for the cycle it covers and is
   raised on the first day of that cycle; `dueDays` on the
   reseller's billing config is how long they have to pay it.
   While the licences are held, billing carries on cycle after
   cycle (a new 12-month term simply follows the last one).

   The price, tax rate and billing cycle are locked on the order
   when it is approved — changing a reseller's plan or cycle later
   only affects what they buy from then on.

   Invoices are generated by the daily job (resellerScheduler.js),
   by an admin pressing "Run Reseller Billing Now", and straight
   away when an order is approved. All of them are safe to repeat:
   one invoice per order per cycle, enforced by a unique index.
============================================================ */

const CYCLE_MULTIPLIER = { monthly: 1, quarterly: 3, yearly: 12 };
const DAY_MS = 24 * 60 * 60 * 1000;
const round2 = (n) => Math.round(n * 100) / 100;

let invoiceCounter = 0;
const generateInvoiceNumber = async () => {
  const count = await ResellerInvoice.countDocuments();
  invoiceCounter = Math.max(invoiceCounter, count) + 1;
  return `INV-RP-${String(invoiceCounter).padStart(5, "0")}`;
};

// 6 Oct + 3 months = 6 Jan. A start on the 31st lands on the last day of
// a shorter month (31 Jan + 1 month = 28/29 Feb) instead of spilling over.
const addMonths = (date, months) => {
  const start = new Date(date);
  const result = new Date(start);
  result.setDate(1);
  result.setMonth(result.getMonth() + months);
  const lastDay = new Date(result.getFullYear(), result.getMonth() + 1, 0).getDate();
  result.setDate(Math.min(start.getDate(), lastDay));
  return result;
};

/* The billing terms of one purchase, locked on the order. Written when
   the order is approved (see resellerLicenseOrderFulfillment.js). An
   order from before per-purchase billing existed has none, so it is
   given one here the first time it is billed: its cycle starts on the
   day it was approved, and any cycle already covered by an old combined
   invoice that was paid is not charged again. */
const ensureOrderBilling = async (order, { config, startDate, legacy = true } = {}) => {
  if (order.billing?.startDate) return order;

  const billingConfig = config || (await ResellerBillingConfig.findOne({ partnerId: order.partnerId }));
  const cycle = billingConfig?.billingCycle || "monthly";
  const cycleMonths = CYCLE_MULTIPLIER[cycle];
  const monthlyAmount = round2(order.quantity * order.pricing.unitPrice);

  let legacyCoveredUntil;
  if (legacy) {
    const lastPaid = await ResellerInvoice.findOne({
      partnerId: order.partnerId,
      purchaseOrderId: { $exists: false },
      paymentStatus: "paid"
    }).sort({ billingPeriodEnd: -1 });
    legacyCoveredUntil = lastPaid?.billingPeriodEnd;
  }

  order.billing = {
    cycle,
    cycleMonths,
    termMonths: RESELLER_LICENSE_TERM_MONTHS,
    startDate: startDate || order.approval?.approvedAt || order.createdAt,
    monthlyAmount,
    cycleAmount: round2(monthlyAmount * cycleMonths),
    termAmount: round2(monthlyAmount * RESELLER_LICENSE_TERM_MONTHS),
    dueDays: billingConfig?.dueDays ?? 7,
    legacyCoveredUntil
  };
  await order.save();
  return order;
};

// The n-th cycle (0-based) of an order: when it starts, ends, and its
// place in the 12-month term ("2 of 4").
const cycleOf = (order, index) => {
  const { startDate, cycleMonths, termMonths } = order.billing;
  const installmentsInTerm = Math.max(1, Math.round(termMonths / cycleMonths));
  return {
    index,
    periodStart: addMonths(startDate, index * cycleMonths),
    periodEnd: addMonths(startDate, (index + 1) * cycleMonths),
    installmentNumber: (index % installmentsInTerm) + 1,
    installmentsInTerm
  };
};

const amountsOf = (order) => {
  const subtotal = order.billing.cycleAmount;
  const taxRatePercent = order.pricing.taxRatePercent;
  const taxAmount = round2((subtotal * taxRatePercent) / 100);
  return { subtotal, taxRatePercent, taxAmount, total: round2(subtotal + taxAmount) };
};

/* Raises every bill that has fallen due for ONE purchase: one per cycle
   whose first day has arrived. Existing invoices are never changed.
   Returns the invoices created by this call. */
const generateInvoicesForOrder = async (orderDoc, { now = new Date(), performedByUserId } = {}) => {
  const order = await ensureOrderBilling(orderDoc);
  const created = [];
  const amounts = amountsOf(order);

  for (let index = 0; ; index += 1) {
    const cycle = cycleOf(order, index);
    if (cycle.periodStart > now) break;
    if (order.billing.legacyCoveredUntil && cycle.periodStart < order.billing.legacyCoveredUntil) continue;

    const exists = await ResellerInvoice.exists({ purchaseOrderId: order._id, billingPeriodStart: cycle.periodStart });
    if (exists) continue;

    let invoice;
    try {
      invoice = await ResellerInvoice.create({
        partnerId: order.partnerId,
        purchaseOrderId: order._id,
        orderCode: order.orderCode,
        invoiceNumber: await generateInvoiceNumber(),
        billingCycle: order.billing.cycle,
        billingPeriodStart: cycle.periodStart,
        billingPeriodEnd: cycle.periodEnd,
        billDate: cycle.periodStart,
        installmentNumber: cycle.installmentNumber,
        installmentsInTerm: cycle.installmentsInTerm,
        purchasedLicenseSnapshot: order.quantity,
        proratedLicenseCount: 0,
        proratedAmount: 0,
        standardUnitPriceSnapshot: order.pricing.standardUnitPrice,
        pricingModeSnapshot: order.pricing.pricingMode,
        wholesaleDiscountPercentSnapshot: order.pricing.wholesaleDiscountPercent,
        fixedUnitPriceSnapshot: order.pricing.fixedUnitPrice,
        unitPriceSnapshot: order.pricing.unitPrice,
        cycleMultiplier: order.billing.cycleMonths,
        ...amounts,
        // Counted from the day the bill is raised. That is the first day
        // of the cycle, unless billing is catching up on an older cycle —
        // a bill raised late is never overdue the moment it appears.
        dueDate: new Date(Math.max(cycle.periodStart.getTime(), Date.now()) + order.billing.dueDays * DAY_MS),
        paymentStatus: "pending"
      });
    } catch (error) {
      // The daily job and an admin can reach this together; the unique
      // (order, cycle) index lets one win and the other carry on.
      if (error.code === 11000) continue;
      throw error;
    }
    created.push(invoice);

    await logActivity({
      partnerId: order.partnerId,
      performedByType: performedByUserId ? "spotx_user" : "system",
      performedByUserId,
      activityType: "reseller_invoice_generated",
      entityType: "ResellerInvoice",
      entityId: invoice._id,
      description: `Invoice ${invoice.invoiceNumber} raised for ${order.quantity} licences (order ${order.orderCode || order._id}) — ${order.billing.cycle} bill ${cycle.installmentNumber} of ${cycle.installmentsInTerm}.`
    });

    await notifyPartner({
      partnerId: order.partnerId,
      type: "reseller_invoice_generated",
      title: "New invoice",
      message: `Invoice ${invoice.invoiceNumber} for ${notifyPartner.rupees(invoice.total)} was raised for your ${order.quantity} licences (order ${order.orderCode}) — ${order.billing.cycle} bill ${cycle.installmentNumber} of ${cycle.installmentsInTerm}. See Billing & Payments.`,
      entityType: "ResellerInvoice",
      entityId: invoice._id
    });
  }

  return created;
};

const billableOrders = (partnerId) =>
  ScreenLicensePurchaseOrder.find({ partnerId, status: "paid" }).sort({ createdAt: 1 });

/* Raises whatever is due across all of one reseller's purchases. Returns
   the invoices created by this call (often none — nothing new was due). */
const generateInvoiceForPartner = async (partnerId, { now = new Date(), performedByUserId } = {}) => {
  // An unpaid invoice from the old one-combined-bill-per-calendar-cycle
  // scheme is replaced by the per-purchase bills below.
  await ResellerInvoice.deleteMany({ partnerId, purchaseOrderId: { $exists: false }, paymentStatus: { $ne: "paid" } });

  const created = [];
  for (const order of await billableOrders(partnerId)) {
    created.push(...(await generateInvoicesForOrder(order, { now, performedByUserId })));
  }
  return created;
};

/* The reseller's bills, one per purchase, each with the instalments of
   its current 12-month term: which have been invoiced (and whether they
   are paid) and which are still to come, with their dates and amounts.
   Read-only — this is what the Billing page shows. */
const getBillingSchedule = async (partnerId, { now = new Date() } = {}) => {
  const orders = await billableOrders(partnerId);
  const bills = [];

  for (const orderDoc of orders) {
    const order = await ensureOrderBilling(orderDoc);
    const { cycleMonths, termMonths, startDate } = order.billing;
    const installmentsInTerm = Math.max(1, Math.round(termMonths / cycleMonths));
    const amounts = amountsOf(order);

    // Which 12-month term today falls in (0 = the first).
    let currentIndex = 0;
    while (cycleOf(order, currentIndex).periodEnd <= now) currentIndex += 1;
    const termIndex = Math.floor(currentIndex / installmentsInTerm);

    const invoices = await ResellerInvoice.find({ purchaseOrderId: order._id }).lean();
    const invoiceByStart = new Map(invoices.map((invoice) => [new Date(invoice.billingPeriodStart).getTime(), invoice]));

    const installments = [];
    for (let i = 0; i < installmentsInTerm; i += 1) {
      const cycle = cycleOf(order, termIndex * installmentsInTerm + i);
      const invoice = invoiceByStart.get(cycle.periodStart.getTime());
      installments.push({
        number: cycle.installmentNumber,
        periodStart: cycle.periodStart,
        periodEnd: cycle.periodEnd,
        billDate: cycle.periodStart,
        dueDate: new Date(cycle.periodStart.getTime() + order.billing.dueDays * DAY_MS),
        ...amounts,
        status: invoice ? invoice.paymentStatus : "upcoming",
        invoiceId: invoice?._id || null,
        invoiceNumber: invoice?.invoiceNumber || null
      });
    }

    const taxOnTerm = round2((order.billing.termAmount * amounts.taxRatePercent) / 100);
    bills.push({
      orderId: order._id,
      orderCode: order.orderCode,
      quantity: order.quantity,
      unitPrice: order.pricing.unitPrice,
      purchasedOn: startDate,
      billingCycle: order.billing.cycle,
      cycleMonths,
      termMonths,
      termStart: cycleOf(order, termIndex * installmentsInTerm).periodStart,
      termEnd: cycleOf(order, (termIndex + 1) * installmentsInTerm).periodStart,
      monthlyAmount: order.billing.monthlyAmount,
      cycleAmount: order.billing.cycleAmount,
      termAmount: order.billing.termAmount,
      taxRatePercent: amounts.taxRatePercent,
      termTaxAmount: taxOnTerm,
      termTotal: round2(order.billing.termAmount + taxOnTerm),
      installments
    });
  }

  // Newest purchase first.
  return bills.reverse();
};

/* The line items behind one invoice, for the "view details" popup. A
   per-purchase invoice has exactly one: the purchase it bills. An invoice
   from the old combined scheme lists every purchase it covered. */
const getInvoiceLineItems = async (invoice) => {
  if (invoice.purchaseOrderId) {
    const order = await ScreenLicensePurchaseOrder.findById(invoice.purchaseOrderId).select("quantity createdAt orderCode billing").lean();
    return {
      baseAmount: invoice.subtotal,
      baseLineItems: [{
        orderCode: order?.orderCode || invoice.orderCode || String(invoice.purchaseOrderId),
        quantity: invoice.purchasedLicenseSnapshot,
        purchaseDate: order?.billing?.startDate || order?.createdAt || null,
        unitPrice: invoice.unitPriceSnapshot,
        cycleMultiplier: invoice.cycleMultiplier,
        amount: invoice.subtotal
      }],
      proratedLineItems: []
    };
  }

  const toLineItem = (order) => ({
    orderCode: order.orderCode || String(order._id),
    quantity: order.quantity,
    purchaseDate: order.createdAt,
    unitPrice: order.pricing?.unitPrice,
    cycleMultiplier: invoice.cycleMultiplier,
    amount: order.quantity * order.pricing.unitPrice * invoice.cycleMultiplier
  });
  const [baseOrders, inCycleOrders] = await Promise.all([
    ScreenLicensePurchaseOrder.find({ partnerId: invoice.partnerId, status: "paid", createdAt: { $lt: invoice.billingPeriodStart } })
      .select("quantity createdAt orderCode pricing.unitPrice").sort({ createdAt: -1 }).lean(),
    ScreenLicensePurchaseOrder.find({ partnerId: invoice.partnerId, status: "paid", createdAt: { $gte: invoice.billingPeriodStart, $lt: invoice.billingPeriodEnd } })
      .select("quantity createdAt orderCode pricing.unitPrice").lean()
  ]);
  const baseLineItems = baseOrders.map(toLineItem);
  return {
    baseAmount: baseLineItems.reduce((sum, item) => sum + item.amount, 0),
    baseLineItems,
    proratedLineItems: inCycleOrders.map(toLineItem)
  };
};

/* "Run Reseller Billing Now" and the daily job: raise whatever has fallen
   due for every active reseller. */
const runBillingForAllPartners = async ({ performedByUserId, now = new Date() } = {}) => {
  const partners = await Partner.find({ partnerType: "reseller", status: "active" }).select("_id");

  const results = [];
  for (const partner of partners) {
    try {
      const invoices = await generateInvoiceForPartner(partner._id, { now, performedByUserId });
      results.push({ partnerId: partner._id, invoicesRaised: invoices.length, invoiceNumbers: invoices.map((invoice) => invoice.invoiceNumber) });
    } catch (error) {
      results.push({ partnerId: partner._id, error: error.message });
    }
  }

  return results;
};

// Flips pending/failed invoices past their dueDate to "overdue" — read by
// enforcement logic to decide whether a partner's new allocate / register /
// activate / purchase actions should be blocked.
const markOverdueInvoices = async () => {
  const result = await ResellerInvoice.updateMany(
    { paymentStatus: { $in: ["pending", "failed"] }, dueDate: { $lt: new Date() } },
    { $set: { paymentStatus: "overdue" } }
  );
  return result.modifiedCount || 0;
};

module.exports = {
  generateInvoiceForPartner,
  generateInvoicesForOrder,
  ensureOrderBilling,
  getBillingSchedule,
  getInvoiceLineItems,
  runBillingForAllPartners,
  markOverdueInvoices,
  addMonths,
  CYCLE_MULTIPLIER
};
